Health:
  Flat:
    1: 20
    2: 40
    3: 70
    4: 100
    5: 150
    6: 210
  Percent:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
Attack:
  Flat:
    1: 3
    2: 6
    3: 10
    4: 14
    5: 19
    6: 25
  Percent:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
Defense:
  Flat:
    1: 3
    2: 6
    3: 10
    4: 14
    5: 19
    6: 25
  Percent:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
Accuracy:
  Flat:
    1: 1
    2: 2
    3: 4
    4: 6
    5: 7
    6: 9
Resistance:
  Flat:
    1: 1
    2: 2
    3: 4
    4: 6
    5: 7
    6: 9
Crit Chance:
  Percent:
    1: 1
    2: 2
    3: 4
    4: 6
    5: 7
    6: 9
Crit damage:
  Percent:
    1: 1
    2: 2
    3: 4
    4: 6
    5: 7
    6: 9
Speed:
  Flat:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6