Weapon:
  Attack:
    Flat:
      1: 4
      2: 8
      3: 12
      4: 16
      5: 25
      6: 35
Helmet:
  Health:
    Flat:
      1: 60
      2: 120
      3: 170
      4: 260
      5: 450
      6: 600
Shield:
  Defense:
    Flat:
      1: 4
      2: 8
      3: 12
      4: 16
      5: 25
      6: 35
Gloves:
  Health:
    Flat:
      1: 60
      2: 120
      3: 170
      4: 260
      5: 450
      6: 600
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Attack:
    Flat:
      1: 4
      2: 8
      3: 12
      4: 16
      5: 25
      6: 35
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Defense:
    Flat:
      1: 4
      2: 8
      3: 12
      4: 16
      5: 25
      6: 35
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Crit Chance:
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Crit damage:
    Percent:
      1: 2
      2: 4
      3: 6
      4: 8
      5: 10
      6: 12
Armor:
  Health:
    Flat:
      1: 60
      2: 120
      3: 170
      4: 260
      5: 450
      6: 600
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Attack:
    Flat:
      1: 4
      2: 8
      3: 12
      4: 16
      5: 25
      6: 35
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Defense:
    Flat:
      1: 4
      2: 8
      3: 12
      4: 16
      5: 25
      6: 35
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Accuracy:
    Flat:
      1: 1
      2: 3
      3: 5
      4: 8
      5: 12
      6: 16
  Resistance:
    Flat:
      1: 1
      2: 3
      3: 5
      4: 8
      5: 12
      6: 16
Boots:
  Health:
    Flat:
      1: 60
      2: 120
      3: 170
      4: 260
      5: 450
      6: 600
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Attack:
    Flat:
      1: 4
      2: 8
      3: 12
      4: 16
      5: 25
      6: 35
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Defense:
    Flat:
      1: 4
      2: 8
      3: 12
      4: 16
      5: 25
      6: 35
    Percent:
      1: 1
      2: 2
      3: 4
      4: 6
      5: 8
      6: 10
  Speed:
    Flat:
      1: 1
      2: 2
      3: 3
      4: 4
      5: 5
      6: 6